In [1]:
pip install pyECLAT

Collecting pyECLAT
  Downloading pyECLAT-1.0.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (2.2.2)
Requirement already satisfied: numpy>=1.17.4 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (2.0.2)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->pyECLAT) (1.17.0)
Downloading pyECLAT-1.0.2-py3-none-any.whl (6.3 kB)
Installing collected packages: pyECLAT
Successfully installed pyECLAT-1.0.2

In [3]:
import pandas as pd
from pyECLAT import ECLAT

df = pd.read_csv("/content/drive/MyDrive/MLT /Market_Basket_Optimisation.csv", header=None)
eclat = ECLAT(data=df)
indices, support = eclat.fit(min_support=0.03,
                             min_combination=2,
                             max_combination=3)


result = pd.DataFrame({
    "Itemset": list(support.keys()),
    "Support": list(support.values())
})

result = result.sort_values(by="Support", ascending=False)

result.head(20)

Combination 2 by 2

630it [00:13, 47.84it/s]

Combination 3 by 3

7140it [02:25, 49.12it/s]

                              Itemset   Support
4           spaghetti & mineral water  0.059725
10          chocolate & mineral water  0.052660
12               eggs & mineral water  0.050927
8                milk & mineral water  0.047994
15        mineral water & ground beef  0.040928
5             spaghetti & ground beef  0.039195
2               spaghetti & chocolate  0.039195
3                    spaghetti & eggs  0.036528
13                eggs & french fries  0.036395
16  mineral water & frozen vegetables  0.035729
1                    spaghetti & milk  0.035462
11           chocolate & french fries  0.034395
0            pancakes & mineral water  0.033729
17       mineral water & french fries  0.033729
9                    chocolate & eggs  0.033196
6                    milk & chocolate  0.032129
14          green tea & mineral water  0.031063
7                         milk & eggs  0.030796

In [4]:
pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2026.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [5]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth, association_rules

# Load dataset
dataset = pd.read_csv("/content/drive/MyDrive/MLT /Market_Basket_Optimisation.csv", header=None)

# Convert dataset into transaction list
transactions = []

for i in range(len(dataset)):
    transactions.append(
        [str(item) for item in dataset.iloc[i] if pd.notna(item)]
    )

# One-Hot Encoding
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)

df = pd.DataFrame(te_array, columns=te.columns_)

# FP-Growth Algorithm
frequent_itemsets = fpgrowth(
    df,
    min_support=0.01,  # 1%
    use_colnames=True
)

print("Frequent Itemsets:")
print(frequent_itemsets.sort_values(by="support", ascending=False).head(20))

# Generate Association Rules
rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.2
)

# Select useful columns
rules = rules[[
    'antecedents',
    'consequents',
    'support',
    'confidence',
    'lift'
]]

# Sort by Lift
rules = rules.sort_values(by='lift', ascending=False)

print("\nTop 20 Association Rules:")
rules.head(20)

Frequent Itemsets:
     support             itemsets
0   0.238368      (mineral water)
15  0.179709               (eggs)
26  0.174110          (spaghetti)
22  0.170911       (french fries)
31  0.163845          (chocolate)
1   0.132116          (green tea)
19  0.129583               (milk)
50  0.098254        (ground beef)
27  0.095321  (frozen vegetables)
43  0.095054           (pancakes)
16  0.087188            (burgers)
56  0.081056               (cake)
28  0.080389            (cookies)
51  0.079323           (escalope)
2   0.076523     (low fat yogurt)
3   0.071457             (shrimp)
34  0.068391           (tomatoes)
4   0.065858          (olive oil)
5   0.063325    (frozen smoothie)
18  0.062525             (turkey)

Top 20 Association Rules:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

                            antecedents  ...      lift
154                     (herb & pepper)  ...  3.291994
141          (spaghetti, mineral water)  ...  2.907928
116                          (tomatoes)  ...  2.474464
9                              (shrimp)  ...  2.446574
84                (milk, mineral water)  ...  2.418737
140        (ground beef, mineral water)  ...  2.394681
86   (mineral water, frozen vegetables)  ...  2.389991
143               (milk, mineral water)  ...  2.346536
65                               (soup)  ...  2.321232
135                         (spaghetti)  ...  2.291162
134                       (ground beef)  ...  2.291162
130                     (grated cheese)  ...  2.201294
14                          (olive oil)  ...  2.183889
53               (chocolate, spaghetti)  ...  2.152382
15           (olive oil, mineral water)  ...  2.136468
148                 (eggs, ground beef)  ...  2.125563
146          (chocolate, mineral water)  ...  2.112849
142                 (milk, ground beef)  ...  2.110308
81           (spaghetti, mineral water)  ...  2.107549
120                          (red wine)  ...  2.095966

[20 rows x 5 columns]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)